### PR TITLE
Fix description error in doc: majorVersion in MQTT topic should be v2 for version 2.0 of the VDA5050 specification

### PR DESCRIPTION
**Pull request by thkfighter**
## Description

In the doc files,
- a minor error: majorVersion in an MQTT topic, interfaceName/majorVersion/manufacturer/serialNumber/topic, should be v2 for version 2.0 of the VDA5050 specification.
~~- a grammatical mistake: an MQTT topic is published or subscribed to, not "published to".~~

## Checklist

- [x] You have the right to contribute the code/documentation/assets to this project, and you agree to contribute it under the terms of the project's license(s).
- [x] All changes have been made on a separate branch (not master) in a fork.
- [x] The whole project compiles correctly and all tests pass, i.e. `gradlew clean build` succeeds with the changes made, and without unavoidable compiler/toolchain warnings.
- [ ] New tests covering the change have been added, if it is possible / makes sense.
- [x] The documentation has been extended, if necessary.
- [x] The PR contains a proposal for a _well-formed_ commit message that mentions all authors who contributed to the PR.
      (The commits in the PR will be squashed into one commit on the base branch, and your proposed message is intended to be used for this commit. See below for a template you can use for the message. See [this blog post](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) and [this one](https://chris.beams.io/posts/git-commit/#seven-rules) for more on well-formed commit messages.)

## Proposed squash commit message

```
Correct majorVersion in MQTT topics in doc

In the doc files,
* majorVersion in an MQTT topic, interfaceName/majorVersion/
  manufacturer/serialNumber/topic, should be v2 for version 2.0 
  of the VDA5050 specification.
```
~~* An MQTT topic is published or subscribed to, not "published to".~~

### CODE REVIEW

**Comment by swltr** [comment]
@thkfighter Thank you for your contribution! Please note that the pull request description template provided in this project is mandatory. Can you please apply it to your PR description before we merge the PR?

**Comment by swltr** [comment]
@thkfighter The topic names used for 2.0 are definitely wrong - thank you for the fix!
One thing I didn't noticed when first reading your PR, though:
I'd argue that while messages are "published" or "published to a topic", topics are indeed "published to".

**Comment by swltr** [comment]
@thkfighter You reacted with 👍 to my previous comment. Can you change the wording back to "published to", then?

**Comment by thkfighter** [comment]
> @thkfighter You reacted with 👍 to my previous comment. Can you change the wording back to "published to", then?

Done.

**Comment by swltr** [comment]
Merged - thanks for the fix!

**Pull request merged**
